name: winda_collection
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.6.0
  uuid: ^4.4.2
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.2.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

## no dependency_overrides

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

